name: example
description: example for witch doctor
version: 1.0.0
environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  witch_doctor:
    path: ../../witch-doctor-dart

dev_dependencies:
  source_gen: ^4.2.0
  build_runner: ^2.11.0