name: witch_doctor
description: A simple and intuitive dependency injection library for dart.
version: 1.2.1
homepage: https://github.com/CenturyBoys/witch-doctor-dart
repository: https://github.com/CenturyBoys/witch-doctor-dart
issue_tracker: https://github.com/CenturyBoys/witch-doctor-dart/issues

environment:
  sdk: ^3.10.3

dependencies:
  analyzer: ">=6.0.0 <10.0.0"
  build: ">=2.4.0 <5.0.0"
  source_gen: ">=1.5.0 <5.0.0"

dev_dependencies:
  build_runner: ^2.11.0
  lints: ^6.1.0
  test: ^1.29.0
